### PR TITLE
edit-readme

### PR DESCRIPTION
**Pull request by 8itwerk**
Issue #19: Readme - Overvew

### CODE REVIEW

**Comment by 8itwerk** [comment]
Commented out the Build Instuructions as well

**Review by mackfoggia — CHANGES_REQUESTED** [review]
On line 12, address should be addresses right?

**Comment by 8itwerk** [comment]
Fix the address/addresses and fleshed out the "Related Works" section.

**Review by mackfoggia — APPROVED** [review]
All looks great!

**Pull request merged**
